"""
Class 9 - Complex JSON, Explode, Dates & End-to-End PySpark Pipeline

Folder structure expected:
class9_pyspark/
├── class9_pipeline.py
├── data/
│   ├── events.json
│   └── products.csv
└── output/                 # generated by the script

Run:
    spark-submit class9_pipeline.py

Or paste each section into a PySpark/Jupyter notebook in order.
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col,
    explode,
    posexplode,
    array_contains,
    size,
    element_at,
    to_date,
    to_timestamp,
    year,
    month,
    dayofmonth,
    datediff,
    upper,
    udf,
    sum as spark_sum,
    count,
    when,
)
from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    LongType,
    ArrayType,
    MapType,
    DoubleType,
)

# ============================================================
# 1. START SPARK
# ============================================================

spark = (
    SparkSession.builder
    .appName("Class9-ComplexJSON-EndToEndPipeline")
    .master("local[*]")
    .getOrCreate()
)

spark.sparkContext.setLogLevel("WARN")

print("Spark version:", spark.version)


# ============================================================
# 2. READ NESTED JSON
# ============================================================

events_path = "data/events.json"

df = spark.read.json(events_path)

print("\n===== RAW DATA =====")
df.show(truncate=False)

print("\n===== INFERRED SCHEMA =====")
df.printSchema()


# ============================================================
# 3. UNDERSTAND STRUCT / ARRAY / MAP
# ============================================================

# StructType examples:
# user.name
# user.city
# device.type
# device.os

struct_demo = df.select(
    "event_id",
    col("user.name").alias("user_name"),
    col("user.city").alias("user_city"),
    col("device.type").alias("device_type"),
    col("device.os").alias("device_os"),
)

print("\n===== STRUCT / NESTED FIELD ACCESS =====")
struct_demo.show()


# ArrayType example: tags
print("\n===== ARRAY EXAMPLE =====")
df.select(
    "event_id",
    "tags"
).show(truncate=False)


# MapType example: metadata
print("\n===== MAP EXAMPLE =====")
df.select(
    "event_id",
    "metadata"
).show(truncate=False)


# ============================================================
# 4. ARRAY FUNCTIONS
# ============================================================

print("\n===== array_contains() =====")
df.filter(
    array_contains("tags", "electronics")
).select(
    "event_id",
    "user_id",
    "tags"
).show(truncate=False)


print("\n===== size() =====")
df.select(
    "event_id",
    size("tags").alias("tag_count")
).show()


print("\n===== element_at() ON ARRAY =====")
df.select(
    "event_id",
    element_at("tags", 1).alias("first_tag")
).show()


print("\n===== element_at() ON MAP =====")
df.select(
    "event_id",
    element_at("metadata", "browser").alias("browser"),
    element_at("metadata", "app_version").alias("app_version")
).show()


# ============================================================
# 5. EXPLODE ARRAY OF STRUCTS
# ============================================================

# Before explode:
# one row can contain many events.
#
# After explode:
# each event becomes a separate row.

exploded_df = df.select(
    "event_id",
    "user_id",
    col("user.name").alias("user_name"),
    col("user.city").alias("city"),
    col("user.signup_date").alias("signup_date"),
    col("device.type").alias("device_type"),
    col("device.os").alias("device_os"),
    "tags",
    "metadata",
    "event_timestamp",
    explode("events").alias("event"),
)

print("\n===== AFTER EXPLODE =====")
exploded_df.show(truncate=False)


# Extract fields from the exploded struct.
event_df = exploded_df.select(
    "event_id",
    "user_id",
    "user_name",
    "city",
    "signup_date",
    "device_type",
    "device_os",
    "tags",
    "metadata",
    "event_timestamp",
    col("event.event_type").alias("event_type"),
    col("event.product_id").alias("product_id"),
    col("event.price").cast("double").alias("price"),
)

print("\n===== FLATTENED EVENT DATA =====")
event_df.show(truncate=False)


# ============================================================
# 6. POSEXPLODE - BASIC AWARENESS
# ============================================================

print("\n===== posexplode() DEMO =====")

df.select(
    "event_id",
    posexplode("tags").alias("position", "tag")
).show()


# ============================================================
# 7. DATE AND TIMESTAMP FUNCTIONS
# ============================================================

dated_df = (
    event_df
    .withColumn(
        "event_timestamp",
        to_timestamp("event_timestamp")
    )
    .withColumn(
        "signup_date",
        to_date("signup_date")
    )
    .withColumn(
        "event_date",
        to_date("event_timestamp")
    )
    .withColumn(
        "event_year",
        year("event_timestamp")
    )
    .withColumn(
        "event_month",
        month("event_timestamp")
    )
    .withColumn(
        "event_day",
        dayofmonth("event_timestamp")
    )
    .withColumn(
        "days_since_signup",
        datediff(
            to_date("event_timestamp"),
            "signup_date"
        )
    )
)

print("\n===== DATE/TIMESTAMP TRANSFORMATIONS =====")
dated_df.select(
    "event_id",
    "event_timestamp",
    "signup_date",
    "event_date",
    "event_year",
    "event_month",
    "event_day",
    "days_since_signup",
).show()


# ============================================================
# 8. PYTHON UDF - DEMO ONLY
# ============================================================

# The curriculum asks students to understand why Python UDFs
# can be expensive and to prefer built-in Spark functions.
#
# This UDF is intentionally simple so that we can compare it
# with Spark's built-in upper() function.

def make_upper(name):
    if name is None:
        return None
    return name.upper()


upper_udf = udf(make_upper, StringType())

print("\n===== PYTHON UDF DEMO =====")
dated_df.select(
    "user_name",
    upper_udf("user_name").alias("upper_name")
).show()


print("\n===== PREFERRED: BUILT-IN SPARK FUNCTION =====")
dated_df.select(
    "user_name",
    upper("user_name").alias("upper_name")
).show()


# ============================================================
# 9. READ PRODUCT LOOKUP DATA
# ============================================================

products_path = "data/products.csv"

products_df = (
    spark.read
    .option("header", True)
    .option("inferSchema", True)
    .csv(products_path)
)

print("\n===== PRODUCT LOOKUP =====")
products_df.show()

print("\n===== PRODUCT SCHEMA =====")
products_df.printSchema()


# ============================================================
# 10. CLEAN DATA BEFORE JOIN
# ============================================================

# Remove events where:
# - product_id is missing
# - price is missing
# - price is <= 0

clean_df = (
    dated_df
    .filter(col("product_id").isNotNull())
    .filter(col("price").isNotNull())
    .filter(col("price") > 0)
)

print("\n===== CLEANED DATA =====")
clean_df.show(truncate=False)


# ============================================================
# 11. JOIN WITH PRODUCT LOOKUP
# ============================================================

joined_df = (
    clean_df
    .join(
        products_df,
        on="product_id",
        how="left"
    )
)

print("\n===== AFTER PRODUCT JOIN =====")
joined_df.select(
    "event_id",
    "user_id",
    "event_type",
    "product_id",
    "product_name",
    "category",
    "price",
    "event_date"
).show()


# ============================================================
# 12. DATA QUALITY CHECK AFTER JOIN
# ============================================================

print("\n===== RECORDS WITH MISSING PRODUCT LOOKUP =====")

joined_df.filter(
    col("product_name").isNull()
).select(
    "event_id",
    "product_id",
    "price"
).show()


# ============================================================
# 13. AGGREGATION
# ============================================================

# Business question:
# "What is the total product value and number of events
#  for each category on each day?"

daily_category_df = (
    joined_df
    .groupBy(
        "event_date",
        "category"
    )
    .agg(
        spark_sum("price").alias("total_value"),
        count("*").alias("event_count")
    )
    .orderBy(
        "event_date",
        "category"
    )
)

print("\n===== DAILY CATEGORY AGGREGATION =====")
daily_category_df.show()


# ============================================================
# 14. PARTITIONING
# ============================================================

print("\n===== PARTITION COUNT BEFORE OUTPUT =====")
print("Partitions:", daily_category_df.rdd.getNumPartitions())

# For a real large dataset, partitioning should be chosen
# based on data volume and query patterns.
#
# For today's demonstration, we use event_date as the
# storage partition column.

output_path = "output/daily_category"

(
    daily_category_df
    .write
    .mode("overwrite")
    .partitionBy("event_date")
    .parquet(output_path)
)

print("\nParquet output written to:", output_path)


# ============================================================
# 15. READ THE PARQUET OUTPUT BACK
# ============================================================

final_df = spark.read.parquet(output_path)

print("\n===== FINAL PARQUET OUTPUT =====")
final_df.show()

print("\n===== FINAL OUTPUT SCHEMA =====")
final_df.printSchema()


# ============================================================
# 16. EXPLAIN THE EXECUTION PLAN
# ============================================================

print("\n===== EXECUTION PLAN =====")

daily_category_df.explain(True)


# ============================================================
# 17. OPTIONAL: SPARK UI DEMO
# ============================================================

# Run an action and then open the Spark UI in the browser.
#
# Usually:
# http://localhost:4040
#
# Depending on the environment, the port can differ.

print("\nRun the aggregation above and open the Spark UI.")
print("Look for Jobs -> Stages -> Tasks.")
print("Then discuss where the join and aggregation can cause shuffle.")


# ============================================================
# 18. FINAL PIPELINE SUMMARY
# ============================================================

print("""
============================================================
CLASS 9 END-TO-END PIPELINE
============================================================

Nested JSON
    |
    v
Read with PySpark
    |
    v
Inspect Struct / Array / Map
    |
    v
Flatten nested structures
    |
    v
Explode arrays
    |
    v
Clean invalid records
    |
    v
Transform dates/timestamps
    |
    v
Join product lookup
    |
    v
Aggregate
    |
    v
Partition by event_date
    |
    v
Write Parquet
============================================================
""")


# ============================================================
# 19. STOP SPARK
# ============================================================

spark.stop()
